### ISSUE TITLE
`rbtag` makes it difficult to have reproducible builds

### ISSUE THREAD

**Issue by grahamc** [LivingInSyn/rbtag#1]
Hey there, this looks like a pretty cool project! It can be very helpful to embed when something is built, and what version exactly was used to build it.

Unfortunately, both of these features can make it hard to produce perfectly reproducible builds, from reproducible sources. This is something I care about a lot, given my work on Nix and NixOS, and the Nix community's relationship with reproducible-builds.org. 

Here are a couple problems this crate creates, but can easily be remedied.

1. The date is obviously a challenge, since the exact moment will never happen again. There is a standard mechanism for making this reproducible, though, which is the [SOURCE_DATE_EPOCH](https://reproducible-builds.org/specs/source-date-epoch/). This is easy to follow. Essentially, if this environment variable is specified during build, use it for the build time instead of asking the kernel for the time.

2. The git repository, and reproducible source is more complicated. It is very difficult for two git clones to be bit-by-bit identical. Even if you check out the exact same commit, delete all the tags and branches, the packfiles are still not the same. For this reason, it is very common to delete the `.git` directory. Sometimes, to work around this, we have to either patch source to avoid  a call to `git`, or create a fake `git` binary which returns canned output. Both of these are pretty annoying and solvable a different way. For this case, I propose you examine an environment variable for the commit description. If it is set, use it. If it isn't set, call `git`.

I hope you can appreciate the goal of reproducible builds, and together we can make a more reproducible and safe software future!

Thank you for your attention :)

**Comment by LivingInSyn** [comment]
These issues are really important, you're correct. I'll definitely be looking into these issues and creating a fix for them. Time is definitely problematic, and I didn't really consider it at first.

Thank you for your feedback 👍

**Comment by grahamc** [comment]
On Twitter you said you might delete build date support, but I would like to ask you to _not_ remove it! A surprise, I suspect, but let me explain.

People are going to want this feature. They'll either get an external crate to do it, or they'll implement it on their own. If rbtag becomes "the crate to use", and rbtag implements both build date tagging and `SOURCE_DATE_EPOCH`, then everybody wins. If rbtag doesn't implement build date tagging, then people are going to implement it themselves, and we'll have to stamp out this scourge of unreproducibility in a million crates.

**Comment by LivingInSyn** [comment]
Please check out the following branch:

https://github.com/LivingInSyn/rbtag/tree/add_helper_methods

This should fix the reproducibility concerns, and barring any other issues, I'll merge and publish

**Comment by LivingInSyn** [comment]
Closed in 0.2.0

https://github.com/LivingInSyn/rbtag/pull/2
