### ISSUE TITLE
Stop printing `build dt called` on every build

### ISSUE THREAD

**Issue by peddermaster2** [LivingInSyn/rbtag#3]
Hello, first of all, thank you for this crate.

I find it very noise to print to stdout on every build. Is it possible to remove [this line](https://github.com/LivingInSyn/rbtag/blob/70db314b3b31cdccabdde9c7e53802eae10eac95/rbtag_derive/src/lib.rs#L51)?

I even noticed that this `println!` breaks the RLS.

**Comment by LivingInSyn** [comment]
Should be in rbtag v0,3,0 on crates.io now.

Thanks!

**Comment by peddermaster2** [comment]
Yes, it work as expected now. Thank you!
